name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm 6.14.16
        run: npm i -g npm@6.14.16 --registry=https://registry.npmjs.org
      - name: Overwrite SSH with access token for private repos
        run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/
      - name: Overwrite HTTPS with access token for private repos
        run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf https://github.com/
      - name: Install dependencies
        run: npm i
      - name: Lint code
        run: npm run lint
      - name: Run unit tests
        run: npm test

  fail-report:
    if: ${{ failure() }}
    needs: unit-tests
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message with fail report
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CI_TELEGRAM_TO }}
          token: ${{ secrets.CI_TELEGRAM_TOKEN }}
          format: markdown
          message: |
            ❌ **${{ github.repository }}** - Workflow: ${{ github.workflow }}
            [Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for commit "[${{ github.event.commits[0].message }}](https://github.com/${{ github.repository }}/commit/${{github.sha}})" (${{github.actor}})
